kind: pipeline
name: default

steps:
- name: test
  image: maven:3-jdk-10
  commands:
  - mvn install
  - mvn test
  
- name: docker  
  image: plugins/docker
  settings:
    # registry: docker.io
    repo: pavansa/vaja
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest
